_prefs: 
  saveCenter: true
_properties: {}
attribution: "<a href='http://mapbox.com/about/maps' target='_blank'>Terms & Feedback</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -0.18792629241949044
  - 51.45521030137689
  - 15
description: A painstakingly hand-drawn representation of the entire world. 2B graphite on acid-free paper.
format: "png8:m=h"
interactivity_layer: ''
layers: null
maxzoom: 21
minzoom: 0
name: Pencil
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v5,mapbox.mapbox-bathymetry-v1"
styles: 
  - style.mss
  - road.mss
  - terrain.mss
template: ''
